export const DEMO_NAME = "pelda_polc.cix";

export const DEMO_CIX = `; Independent synthetic workshop demo
BEGIN MAINDATA
  LPX=720
  LPY=380
  LPZ=18
END MAINDATA

BEGIN MACRO
  NAME=BG
  PARAM,NAME=SIDE,VALUE=0
  PARAM,NAME=X,VALUE=30
  PARAM,NAME=Y,VALUE=35
  PARAM,NAME=Z,VALUE=0
  PARAM,NAME=DP,VALUE=12
  PARAM,NAME=DIA,VALUE=5
  PARAM,NAME=RTY,VALUE=rpXY
  PARAM,NAME=DX,VALUE=32
  PARAM,NAME=DY,VALUE=0
  PARAM,NAME=NRP,VALUE=21
  PARAM,NAME=LAY,VALUE="Polctarto furatok"
END MACRO

BEGIN MACRO
  NAME=BG
  PARAM,NAME=SIDE,VALUE=0
  PARAM,NAME=X,VALUE=30
  PARAM,NAME=Y,VALUE=345
  PARAM,NAME=Z,VALUE=0
  PARAM,NAME=DP,VALUE=12
  PARAM,NAME=DIA,VALUE=5
  PARAM,NAME=RTY,VALUE=rpXY
  PARAM,NAME=DX,VALUE=32
  PARAM,NAME=DY,VALUE=0
  PARAM,NAME=NRP,VALUE=21
  PARAM,NAME=LAY,VALUE="Polctarto furatok"
END MACRO

BEGIN MACRO
  NAME=ROUT
  PARAM,NAME=SIDE,VALUE=0
  PARAM,NAME=DP,VALUE=8
  PARAM,NAME=DIA,VALUE=8
  PARAM,NAME=LAY,VALUE="Horony"
END MACRO
BEGIN MACRO
  NAME=START_POINT
  PARAM,NAME=X,VALUE=10
  PARAM,NAME=Y,VALUE=190
  PARAM,NAME=Z,VALUE=0
END MACRO
BEGIN MACRO
  NAME=LINE_EP
  PARAM,NAME=XE,VALUE=710
  PARAM,NAME=YE,VALUE=190
  PARAM,NAME=ZE,VALUE=0
END MACRO
BEGIN MACRO
  NAME=ENDPATH
END MACRO`;
